---
- hosts: aws_ec2
  become: yes
  connection: ssh
  user: ec2-user

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/sshkey.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: Install Tomcat
      action: yum name=httpd state=present
    - name: Restart httpd
      service: name=httpd state= restarted
    - name: Install Git
      action: yum name=git state=present
    - name: clone the repo
      git: 
         repo: https://github.com/Bindulatha9/myweb.git
         dest: /var/www/html/
         version: main
